services:
  # Backend API service
  - type: web
    name: plantperfectly-api
    env: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: CLIENT_URL
        fromService:
          name: plantperfectly-client
          type: web
          property: url
      - key: FORCE_PRODUCTION_EMAIL
        value: "true"
      - key: EMAIL_HOST
        value: smtp-relay.brevo.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_SECURE
        value: "false"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: noreply@plantperfectly.com
    healthCheckPath: /api/health

  # Frontend client service
  - type: web
    name: plantperfectly-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: plantperfectly-api
          type: web
          property: url
      - key: REACT_APP_ENV
        value: production 